# Generated by Django 4.2 on 2023-04-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_profile_profile_image"),
        ("user", "0004_alter_profile_user"),
    ]

    operations = []
