# Generated by Django 4.2 on 2023-04-14 02:49

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="post",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
