# Generated by Django 4.2 on 2023-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_comment_content_alter_post_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="댓글 작성"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post",
            field=models.TextField(),
        ),
    ]
