# Generated by Django 4.2 on 2023-04-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
